# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package testing

on:
  push:
    branches: [ master, pre-release ]
  pull_request:
    branches: [ master, pre-release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v7
    - name: Install dependencies
      run: |
        poetry update
        poetry build
    - name: Test with pytest
      run: |
        cd ./dist
        poetry run pytest ../
    - uses: actions/upload-artifact@v2
      with:	
        name: easyCore - Python ${{ matrix.python-version }}
        path: ${{ github.workspace }}/dist/*

#   deploy:
#     runs-on: ubuntu-latest
#     needs: [ build ]
#     strategy:
#       matrix:
#         python-version: [3.7]
#     if: "!contains(github.event.head_commit.message, '[ci skip]')"
#     steps:
#       - uses: actions/checkout@master
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}
#       - uses: actions/download-artifact@master
#         with:
#           name: easyCore - Python ${{ matrix.python-version }}
#           path: ${{ github.workspace }}/dist/*
#       - name: Publish distribution ðŸ“¦ to Test PyPI
#         uses: pypa/gh-action-pypi-publish@master
#         with:
#           password: ${{ secrets.PYPI_TESTTOKEN }}
#           repository_url: https://test.pypi.org/legacy/
